databases:
  - name: dicsmeal
    databaseName:
    user: dicsmeal
    region: singapore
    plan: free

services:
  - type: web
    name: dicsmeal
    runtime: python
    plan: free
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dicsmeal
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
