databases:
  - name: dics-meal-backend
    databaseName: dics-meal-backend
    user: dics-meal-backend
    region: singapore

services:
  - type: web
    name: dics-meal-backend
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dics-meal-backend
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
