services:
  - type: web
    name: dicsmeal
    runtime: python
    plan: free
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn meal_upload.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
